### ISSUE TITLE
Passing credentials doesn't work

### ISSUE THREAD

**Issue by 9Mad-Max5** [simao-silva/noip-renewer#1]
I didn't made it to pass the credentials.
Without <> it doesn't work rather with <> and with "" it as well don't excepts them.

**Comment by simao-silva** [comment]
Does your password have special characters? If it does, you must escape them.
The <> are only indicative. You must pass the credentials preferably with quotation marks: `"your password here"`.

**Comment by 9Mad-Max5** [comment]
I don't have any special characters in my password.
So I tried it bare directly in the string.
I already tried escaping both the mail and the password with ".
Like "mail" "password"

But still I was asked later for the mail and the password.

**Comment by 9Mad-Max5** [comment]
ok just pulled and seems to work.

**Comment by simao-silva** [comment]
That's odd. In the meantime, I've uploaded a new version with a different base image. 
Glad it is resolved.
