### ISSUE TITLE
No-IP language need to be set to English in order for the renewer to work

### ISSUE THREAD

**Issue by rastaralle** [simao-silva/noip-renewer#11]
Hi Simao Silva,

during an unsuccessful attempt to get your renewer working, I noticed that the renew.py is searching for a button with the exact test "confirm" in the hosts list. This only is the case if the language is set to English in the No-IP settings.

After I changed to English language in my personal settings on No-IP homepage, your renewer worked like a charm.

As there might be more people running into the same issue, it might be worth mentioning this in the readme.

BTW: Excellent tool!

BR 
Ralf

**Comment by simao-silva** [comment]
Instead of restricting exclusively to English maybe you can open a PR with the translated name of the confirmation button. Just add an `or` in the `if` condition.

**Comment by simao-silva** [comment]
It should now work with any language.
