### ISSUE TITLE
user agent not passed correctly

### ISSUE THREAD

**Issue by Exceen** [simao-silva/noip-renewer#136]
hi! just wanted to point out that you are missing 2 leading '-' for the user agent to work properly

that line should look like

`browser_options.add_argument("--user-agent=" + get_user_agent())`

https://github.com/simao-silva/noip-renewer/blob/040b95e5e62d73ccbd71f7ca2c9d0036400a281b/renew.py#L83

appreciate your work!

**Comment by simao-silva** [comment]
Fixed in #146 .
