### ISSUE TITLE
not able to build image locally

### ISSUE THREAD

**Issue by hsuyao** [simao-silva/noip-renewer#15]
Hi Sir,

I've tried to build image locally with the instruction in the README.md, there are many of error messages.
I am not sure if something was going wrong with it.

**Comment by simao-silva** [comment]
Hi,
There was missing the correct file to be used to build locally. In the mean time, I have already pushed it to the repository so check the new changes. You should be able to run it without problems.

**Comment by hsuyao** [comment]
Thanks, I will try it and give the feedback for you.
