### ISSUE TITLE
timezone info

### ISSUE THREAD

**Issue by habuild** [simao-silva/noip-renewer#16]
Perhaps this is a me issue..
Thanks muchly for this container! makes noip much more user friendly!

I only run this addon twice a week, so I usually go and check the logs when it around renew dates.
I run it around 3am, and I am about 10 hours ahead of UTC time.
So when I go and look the logs, the times are a bit confusing at first glance when they are in UTC timezone.

I have tried adding /etc/localtime:/etc/localtime as a bind or TZ mycountry/mycity as an environment. That fixes the date inside the container.. 
The logs still print as UTC after that though. 
I was fiddling a bit with renew.py to no avail. 

I tried
`from datetime import tzinfo`

Is there a simple fix to updating the output of the logs?
Quite happy to add either the bind or ENV variable.

Sorry I am not a very good programmer and even worse with python.

```
2022-10-14T12:25:25.628582000Z Opening browser
2022-10-14T12:25:37.890734000Z Error: cannot login. Check if account is not blocked.  ## I had fake details here
2022-10-14T12:25:37.892266000Z Logging off
2022-10-14T12:25:37.892598000Z
2022-10-14T12:25:37.893855000Z

```

**Comment by simao-silva** [comment]
Hi,
I will not add this in the near future due to lack of time. Maybe you can open a PR with the changes you have added so that someone can pick up and improve your work?

**Comment by habuild** [comment]
Thanks for the consideration.
Understandable about the lack of time.
I don't have any changes for a PR that makes it close to working.
So best just to close and ignore I think.
Thanks.
