### ISSUE TITLE
Enter 2FA Key is prompted when account has 2FA disabled

### ISSUE THREAD

**Issue by sitymarz** [simao-silva/noip-renewer#198]
Just by running

docker run --rm -it simaofsilva/noip-renewer:latest USERNAME PASSWORD

I keep getting the prompt
Enter 2FA key:

**Comment by simao-silva** [comment]
Did you receive a confirmation code in your e-mail?

**Comment by sitymarz** [comment]
> Did you receive a confirmation code in your e-mail?

Just checked and it looks like I was getting a confirmation code.
Not sure why I was as my Account states 2FA is disabled.

**Comment by simao-silva** [comment]
You were asked for the 2FA because I found out that both 2FA and email verification steps use the same URL. However, I was able to fix that in #199 . Please try the latest version to overcome that error.
