### ISSUE TITLE
The latest version (5b53751) is unable to use TOTP. 

### ISSUE THREAD

**Issue by ray1025** [simao-silva/noip-renewer#200]
When attempting to use TOTP with the latest version (5b53751), it times out and displays "Could not login. Check if account is blocked.". However, TOTP works fine with the previous version (bfdfa01).

**Comment by ray1025** [comment]
Just to add, I'm using this method to run Docker: 
docker run --rm --env NO_IP_USERNAME=<EMAIL> --env NO_IP_PASSWORD=<PASSWORD> --env NO_IP_TOTP_KEY=<NOIP TOTP KEY> simaofsilva/noip-renewer

**Comment by ray1025** [comment]
I've tried using two sets of accounts separately, each for four attempts, and the results are the same. Now, when I use the previous version, everything works fine.

**Comment by ray1025** [comment]
Additionally, I've found that running the latest version using the command `docker run --rm -it simaofsilva/noip-renewer` works fine.

**Comment by ray1025** [comment]
However, since I need to automate the scheduling, I prefer using the method `docker run --rm --env NO_IP_USERNAME="EMAIL" --env NO_IP_PASSWORD="PASSWORD" --env NO_IP_TOTP_KEY="KEY" simaofsilva/noip-renewer`.

**Comment by D4rkT1m0** [comment]
> Did you try rerun it? When you login on your NOIP account through the browser does the dashboard page loads right after you login?

hello there,
I got the same error message ("Could not login. Check if account is blocked.")
until  today, i didn't enable the 2FA in noip.
I therefore encountered the mail OTP with 6 digits.

I then activate the 2FA in noip.com and saved the key.
on the website, when i logout and sign in again, I am not prompt for the mail OTP.

now, I modify my script to match the command line including the NO_IP_TOTP_KEY

but I'm still stuck at "Could not login. Check if account is blocked."

any idea?

**Comment by johngianni** [comment]
> > Did you try rerun it? When you login on your NOIP account through the browser does the dashboard page loads right after you login?
> 
> hello there, I got the same error message ("Could not login. Check if account is blocked.") until today, i didn't enable the 2FA in noip. I therefore encountered the mail OTP with 6 digits.
> 
> I then activate the 2FA in noip.com and saved the key. on the website, when i logout and sign in again, I am not prompt for the mail OTP.
> 
> now, I modify my script to match the command line including the NO_IP_TOTP_KEY
> 
> but I'm still stuck at "Could not login. Check if account is blocked."
> 
> any idea?

Same here!

**Comment by zhouyuyu888** [comment]
> > > Did you try rerun it? When you login on your NOIP account through the browser does the dashboard page loads right after you login?
> > 
> > 
> > hello there, I got the same error message ("Could not login. Check if account is blocked.") until today, i didn't enable the 2FA in noip. I therefore encountered the mail OTP with 6 digits.
> > I then activate the 2FA in noip.com and saved the key. on the website, when i logout and sign in again, I am not prompt for the mail OTP.
> > now, I modify my script to match the command line including the NO_IP_TOTP_KEY
> > but I'm still stuck at "Could not login. Check if account is blocked."
> > any idea?
> 
> Same here!
> 
> Running it from command line in a synology NAS with the following command:
> 
> docker run --rm -it --shm-size=2g --env NO_IP_USERNAME=xxxxx --env NO_IP_PASSWORD=xxxxx --env NO_IP_TOTP_KEY=xxxxxxx simaofsilva/noip-renewer

me too,display:
Using user agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
Opening browser
Could not login. Check if account is blocked.

I use browser can login and update ddns name。

**Comment by ray1025** [comment]
@simao-silva 
I think I found the problem. Please check the Pull requests.

**Comment by johngianni** [comment]
For me it's still not working. I've cloned the repo and build locally.

**Comment by ray1025** [comment]
@johngianni 
Try using the Docker image I built: raymond1025/noip-renewer.

**Comment by ray1025** [comment]
The login page for noip has been redesigned again...

**Comment by ray1025** [comment]
The new issue now is:
Message: Element <input id="challenge_code" name="challenge_code" type="hidden"> is not reachable by keyboard

**Comment by ray1025** [comment]
The new issue now is:`Message: Element <input id="challenge_code" name="challenge_code" type="hidden"> is not reachable by keyboard`

**Comment by ray1025** [comment]
@simao-silva 
I made some rough modifications. Please try this one out: #211

**Comment by ray1025** [comment]
@johngianni 
Try using the Docker image I built: raymond1025/noip-renewer

**Comment by simao-silva** [comment]
Seems to be working. #211 merged. 
Great job @ray1025!

**Comment by D4rkT1m0** [comment]
the update makes it running fine, thank you

**Comment by daNutzzzzz** [comment]
Hi, im still getting account blocked...

```
docker run --rm --name=noip-renewer --network=bridge-net --env NO_IP_USERNAME=REDCATED --env NO_IP_PASSWORD=REDCATED --env NO_IP_TOTP_KEY=REDCATED simaofsilva/noip-renewer:latest
Using user agent "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:109.0) Gecko/20100101 Firefox/121.0"
Opening browser
Could not login. Check if account is blocked.
```
