### ISSUE TITLE
geckodriver- raspi2

### ISSUE THREAD

**Issue by bigoth** [simao-silva/noip-renewer#22]
hi,
can you verif your docker. since 2 weeks i have this bug.  i look on my rp2 but i think its the docker who crash.

Digest: sha256:55ab8d7ea92042670feab6d2923589b733d666cdef635801d56cd614645ccb16
Status: Downloaded newer image for simaofsilva/noip-renewer:debian
docker.io/simaofsilva/noip-renewer:debian
Status: Image is up to date for simaofsilva/noip-renewer:debian

Opening browser
Traceback (most recent call last):
  File "//renew.py", line 60, in <module>
    browser = webdriver.Firefox(options=browserOptions)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 192, in __init__
    self.service.start()
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 90, in start
    self._start_process(self.path)
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 199, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'geckodriver'

thx if you can check

**Comment by bigoth** [comment]
hi i edit your dockerfile


download   https://github.com/simao-silva/noip-renewer/archive/refs/heads/master.zip
i unzip master.zip
i edit  dockerfile ARG PIP_VERSION  ---> ARG PIP_VERSION="22.3.1"
and rebuild.
sudo docker build -t no_ip:latest .
and now its work fine for "raspi2 arm7 32bits"
sudo docker run --rm -it --name noip no_ip:latest  LOGIN PASSWORD


FROM python:3.11.1-alpine@sha256:af8fef83397b3886ed93d2c81bf3b4e70d39c0789c1c6feb1ecb86ca9bc42a0a

ARG PIP_VERSION="22.3.1"

COPY requirements.txt /requirements.txt

RUN apk add --no-cache gcc libc-dev libffi-dev && \
    pip install --no-cache-dir pip=="$PIP_VERSION" && \
    pip install --no-cache-dir --user -r /requirements.txt


FROM python:3.11.1-alpine@sha256:af8fef83397b3886ed93d2c81bf3b4e70d39c0789c1c6feb1ecb86ca9bc42a0a

RUN apk add --no-cache firefox && \
    apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing geckodriver && \
    # Added patched versions from Trivy scan
    apk upgrade krb5-libs && \
    rm -rf /var/cache/apk/* /tmp/*

COPY --from=0 /root/.local /root/.local

ENV PATH=/root/.local/bin:$PATH

COPY renew.py .

ENTRYPOINT ["python3", "renew.py"]

**Comment by simao-silva** [comment]
Geckodriver's repository does not provide an artifact for arm v7. Although I provide an image for arm v7, the geckodriver installed seems to work in some devices but it might not work in others.
