### ISSUE TITLE
unable to use TOTP

### ISSUE THREAD

**Issue by daNutzzzzz** [simao-silva/noip-renewer#221]
Hi, linked to https://github.com/simao-silva/noip-renewer/issues/200

im still getting account blocked...

```
docker run --rm --name=noip-renewer --network=bridge-net --env NO_IP_USERNAME=REDCATED --env NO_IP_PASSWORD=REDCATED --env NO_IP_TOTP_KEY=REDCATED simaofsilva/noip-renewer:latest
Using user agent "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:109.0) Gecko/20100101 Firefox/121.0"
Opening browser
Could not login. Check if account is blocked.
```

**Comment by simao-silva** [comment]
Hi,
Can you again using image `simaofsilva/noip-renewer:c01467b-alpine`?

**Comment by daNutzzzzz** [comment]
> Hi, Can you again using image `simaofsilva/noip-renewer:c01467b-alpine`?

`Using user agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15"
Opening browser
Could not login. Check if account is blocked.
`

**Comment by simao-silva** [comment]
Can you login on a browser without issues? Are you redirected to the dashboard right after you enter the TOTP code?

**Comment by ray1025** [comment]
You mentioned that you've pulled the latest image, your computer's clock is correct, and your account is fine. The last issue might be an incorrect TOTP_KEY. Please make sure to double-check your TOTP_KEY. The TOTP_KEY is displayed only once when you initially enable 2FA, right under the QR code. If you didn't save it, you can disable and then re-enable 2FA to generate a new one. For more details, please refer to [this link](https://github.com/simao-silva/noip-renewer/issues/189#issuecomment-2100240986).

**Comment by ray1025** [comment]
Here is the script I use for automated execution. It has been running successfully for over 10 days:
```bash
docker pull simaofsilva/noip-renewer
docker run --rm --env NO_IP_USERNAME="EMAIL" --env NO_IP_PASSWORD="PASSWORD" --env NO_IP_TOTP_KEY="KEY" simaofsilva/noip-renewer
```

**Comment by daNutzzzzz** [comment]
> You mentioned that you've pulled the latest image, your computer's clock is correct, and your account is fine. The last issue might be an incorrect TOTP_KEY. Please make sure to double-check your TOTP_KEY. The TOTP_KEY is displayed only once when you initially enable 2FA, right under the QR code. If you didn't save it, you can disable and then re-enable 2FA to generate a new one. For more details, please refer to [this link](https://github.com/simao-silva/noip-renewer/issues/189#issuecomment-2100240986).

#
Hi Ray, that is the key im using

**Comment by daNutzzzzz** [comment]
> Here is the script I use for automated execution. It has been running successfully for over 10 days:
> 
> ```shell
> docker pull simaofsilva/noip-renewer
> docker run --rm --env NO_IP_USERNAME="EMAIL" --env NO_IP_PASSWORD="PASSWORD" --env NO_IP_TOTP_KEY="KEY" simaofsilva/noip-renewer
> ```

Pretty much the same as mine

**Comment by ray1025** [comment]
@daNutzzzzz 
Please use this image for testing: 
`raymond1025/noip-renewer-dev`
I've added a feature to detect two-factor authentication code errors.

**Comment by daNutzzzzz** [comment]
> @daNutzzzzz Please use this image for testing: `raymond1025/noip-renewer-dev` I've added a feature to detect errors with the two-factor authentication code.

thank you, it said invalid code albeit the one i took from the site so i will reset my 2FA and retry.

**Comment by daNutzzzzz** [comment]
> If you've changed and double-checked your TOTP KEY and are still getting an "Invalid code..." error, it's likely an issue with your device's clock. Could you try using a different device?

Date is correct

![image](https://github.com/simao-silva/noip-renewer/assets/89404081/d60d4393-e269-4178-af5c-f3dfbbb8eb0e)

I'll try another

**Comment by ray1025** [comment]
Please use this image for testing:
`raymond1025/noip-renewer-dev-v2`
In this version, I’ve added a feature to sync the clock using Google's NTP server.

**Comment by daNutzzzzz** [comment]
> Please use this image for testing: `raymond1025/noip-renewer-dev-v2` In this version, I’ve added a feature to sync the clock using Google's NTP server.

thanks, tired on both machines and still "invalid code" :(

**Comment by ray1025** [comment]
Sorry...I'm really out of ideas at this point...

**Comment by Kucharskov** [comment]
Hi guys (mostly @simao-silva)! I have simmilar issue, but my output is a little bit bigger:
```
Using user agent "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:109.0) Gecko/20100101 Firefox/121.0"
Opening browser
Traceback (most recent call last):
  File "/app/renew.py", line 146, in <module>
    totp_input.send_keys(totp.now())
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 231, in send_keys
    self._execute(
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <input id="challenge_code" name="challenge_code" type="hidden"> is not reachable by keyboard
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:353:5
webdriverSendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:668:13
interaction.sendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:642:11
sendKeysToElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:540:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:150:31
```

**Comment by Kucharskov** [comment]
> Hi, Can you again using image `simaofsilva/noip-renewer:c01467b-alpine`?

When i used this specified image it works perfectly :)

**Comment by ray1025** [comment]
@daNutzzzzz 
Do you know how to use GitHub Actions? Would you like to try running it on GitHub Actions? If you need help, I can provide a simple example.

**Comment by simao-silva** [comment]
@daNutzzzzz are you still getting issues with TOTP?

**Comment by daNutzzzzz** [comment]
> @daNutzzzzz are you still getting issues with TOTP?

unfortunately yes and noip support is run by a bot :(

**Comment by simao-silva** [comment]
@daNutzzzzz can you try again using image `simaofsilva/noip-renewer:debug`? Check for line with message `2FA code:` and see if the TOTP code this script is going to use matches the code generate by your TOTP generator app.

**Comment by daNutzzzzz** [comment]
> @daNutzzzzz can you try again using image `simaofsilva/noip-renewer:debug`? Check for line with message `2FA code:` and see if the TOTP code this script is going to use matches the code generate by your TOTP generator app.

Hi, ive just tired and nothing happens, its just sat running for the last 15 minutes..it doesnt finish.

**Comment by daNutzzzzz** [comment]
> jnrbsn.github.io

ok so ive tried again, the issue i have is that it takes so long to process that i run through multiple 2fa code on my auth app to be able to match the code the script outputs.

**Comment by simao-silva** [comment]
Try running with `-e TZ=YOUR TIMEZONE` , e.g. `-e TZ=Europe/London`, and see if the codes still do not match.

**Comment by daNutzzzzz** [comment]
> Try running with `-e TZ=YOUR TIMEZONE` , e.g. `-e TZ=Europe/London`, and see if the codes still do not match.

Hi, i did and no it still fails.

**Comment by sm622** [comment]
Using user agent "Mozilla/5.0 (X11; Linux i686; rv:115.0) Gecko/20100101 Firefox/115.0"
Opening browser
Login successful
Confirming hosts phase
Checking if host "xxxxxxxx.net" needs confirmation
Host "xxxxxxxx.net" confirmed
Error:  Message: The element with the reference 2f1e69f5-af35-4f84-9da4-cc5de0a7de80 is stale; either its node document is not the active document, or it is no longer connected to the DOM; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
StaleElementReferenceError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:725:5
getKnownElement@chrome://remote/content/marionette/json.sys.mjs:401:11
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:259:20
cloneObject@chrome://remote/content/marionette/json.sys.mjs:59:24
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:289:16
cloneObject@chrome://remote/content/marionette/json.sys.mjs:59:24
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:289:16
json.deserialize@chrome://remote/content/marionette/json.sys.mjs:293:10
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:72:30

Logging off

**Comment by daNutzzzzz** [comment]
> Using user agent "Mozilla/5.0 (X11; Linux i686; rv:115.0) Gecko/20100101 Firefox/115.0" Opening browser Login successful Confirming hosts phase Checking if host "xxxxxxxx.net" needs confirmation Host "xxxxxxxx.net" confirmed Error: Message: The element with the reference 2f1e69f5-af35-4f84-9da4-cc5de0a7de80 is stale; either its node document is not the active document, or it is no longer connected to the DOM; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception Stacktrace: RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8 WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5 StaleElementReferenceError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:725:5 getKnownElement@chrome://remote/content/marionette/json.sys.mjs:401:11 deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:259:20 cloneObject@chrome://remote/content/marionette/json.sys.mjs:59:24 deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:289:16 cloneObject@chrome://remote/content/marionette/json.sys.mjs:59:24 deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:289:16 json.deserialize@chrome://remote/content/marionette/json.sys.mjs:293:10 receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:72:30
> 
> Logging off

This has nothing to do with the issue im experiencing, please create your own issue.

**Comment by ray1025** [comment]
@daNutzzzzz 
Hello, I've used Synology NAS, Windows 11, VPS (Ubuntu Server), and GitHub Actions, but I couldn't reproduce the error.
Could you let me know what device you’re running Docker on?

**Comment by ray1025** [comment]
@daNutzzzzz 
If you encounter 2FA errors using GitHub Actions, it really means there’s an issue with your KEY...
Here's the Workflow file I use. You can modify the "docker_image:" to run the image you prefer.

```yml
name: noip-renewer-dev

on:
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    env:
      docker_image: simaofsilva/noip-renewer:debug

    steps:
      - name: Pull noip-renewer
        run: docker pull $docker_image

      - name: Run noip-renewer
        run: docker run --rm --env NO_IP_USERNAME="${{ secrets.NOIP_USERNAME }}" --env NO_IP_PASSWORD="${{ secrets.NOIP_PASSWORD }}" --env NO_IP_TOTP_KEY="${{ secrets.NOIP_OTP }}" $docker_image
        continue-on-error: true
```

**Comment by daNutzzzzz** [comment]
> @daNutzzzzz Here's the Workflow file I use. You can modify the "docker_image:" to run the image you prefer. For instructions on how to set up secrets, please refer to this [link](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions).
> 
> ```yaml
> name: noip-renewer-dev
> 
> on:
>   workflow_dispatch:
> 
> jobs:
>   checkin:
>     runs-on: ubuntu-latest
>     env:
>       docker_image: simaofsilva/noip-renewer:debug
> 
>     steps:
>       - name: Pull noip-renewer
>         run: docker pull $docker_image
> 
>       - name: Run noip-renewer
>         run: docker run --rm --env NO_IP_USERNAME="${{ secrets.NOIP_USERNAME }}" --env NO_IP_PASSWORD="${{ secrets.NOIP_PASSWORD }}" --env NO_IP_TOTP_KEY="${{ secrets.NOIP_OTP }}" $docker_image
>         continue-on-error: true
> ```
> 
> Screenshot: ![2024-06-06](https://private-user-images.githubusercontent.com/49980364/337053869-cf93efca-faeb-4bd0-891e-7178add91b46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NjY5MzAsIm5iZiI6MTcxNzY2NjYzMCwicGF0aCI6Ii80OTk4MDM2NC8zMzcwNTM4NjktY2Y5M2VmY2EtZmFlYi00YmQwLTg5MWUtNzE3OGFkZDkxYjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA5MzcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YTc4YTVmYTI1NTg1ZjZiNjlhZTU1NWRjNTY1Mjg1Yzg2NGNjNDljNTFlMjEyNTFiNmJhNmJhNjY5ZmNkMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FO-NIOS_Gmc7aCWr-gVY2Dso7h5-_PQk_ELGjNF2BRo)

Thanks Ray,

Ive run this and it failed with the current code, so ive tried disabling and re-enabling 2FA on noip dashboard two more times and finally its now working! both in GH Actions and in my homelab.

Thank you @ray1025 @simao-silva for your continued support with this, it clearly is an issue with the NOIP TOTP keys being issued, that i have raised with them but they dont care.
