### ISSUE TITLE
Finding button issue

### ISSUE THREAD

**Issue by sm622** [simao-silva/noip-renewer#229]
Below is the log

Using user agent "Mozilla/5.0 (X11; Linux i686; rv:115.0) Gecko/20100101 Firefox/115.0"
Opening browser
Login successful
Confirming hosts phase
Checking if host "xxxxxxxx.net" needs confirmation
Host "xxxxxxxx.net" confirmed
Error:  Message: The element with the reference 2f1e69f5-af35-4f84-9da4-cc5de0a7de80 is stale; either its node document is not the active document, or it is no longer connected to the DOM; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
StaleElementReferenceError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:725:5
getKnownElement@chrome://remote/content/marionette/json.sys.mjs:401:11
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:259:20
cloneObject@chrome://remote/content/marionette/json.sys.mjs:59:24
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:289:16
cloneObject@chrome://remote/content/marionette/json.sys.mjs:59:24
deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:289:16
json.deserialize@chrome://remote/content/marionette/json.sys.mjs:293:10
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:72:30

Logging off

**Comment by ray1025** [comment]
Today, I happened to encounter a host that required confirmation. I didn't experience the issue you're facing.
![2024-06-09](https://github.com/simao-silva/noip-renewer/assets/49980364/3dceb2b8-dd7d-4cae-98a7-a20532d7b21f)

**Comment by simao-silva** [comment]
@sm622 Have you tried rerun it? Did you tried in a different device?

**Comment by sm622** [comment]
Thanks for reply

1. I did that manually. So there are no pending requests.
2. I think the above issue is in grace period. Is script able to confirm in 7 days Grace period.

**Comment by simao-silva** [comment]
Yes, the script works when the confirmation in on grace period. 
Since you already confirm your hosts manually, I will close this. Feel free to reopen it if this happens again.
