### ISSUE TITLE
command wont work as a script for some reason. Error 'the input device is not a TTY"

### ISSUE THREAD

**Issue by alirz1** [simao-silva/noip-renewer#24]
im trying to run this command as a schduled task in the synology nas. I've tried running it as a regular user and also as root. However i get an error back.
However if i run the belo command manualy while logged in via ssh, it works fine as teh regular user and also as root.
 
docker run --rm -it simaofsilva/noip-renewer 'nopip-login_email' 'password'

Would you know what this error means?

Task Scheduler has completed a scheduled task.

Task: No-ip-Renew
Start time: Sun, 29 Jan 2023 09:26:02 GMT
Stop time: Sun, 29 Jan 2023 09:26:03 GMT
Current status: 1 (Interrupted)
Standard output/error:
the input device is not a TTY

**Comment by simao-silva** [comment]
Hi,
The `-t` is what is causing that error. 
To run on cron you could do one of the following examples:
```sh
docker run --rm -i simaofsilva/noip-renewer 'noip-login_email' 'password'
# OR
docker run --rm simaofsilva/noip-renewer 'noip-login_email' 'password'
```

**Comment by alirz1** [comment]
> ```shell
> docker run --rm -i simaofsilva/noip-renewer 'noip-login_email' 'password'
> ```

Awesome that worked. Thank you so much for this great tool.

**Comment by simao-silva** [comment]
Glad it worked.
