### ISSUE TITLE
Renewal not working

### ISSUE THREAD

**Issue by cfr2305** [simao-silva/noip-renewer#252]
Hi,
the host confirmation is not working. If I look at the logs it looks good:

```
Using user agent "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:115.0) Gecko/20100101 Firefox/115.0"
Opening browser
Login successful
Confirming hosts phase
Checking if host "*******.ddns.net" needs confirmation
Host "*******.ddns.net" confirmed
1 host confirmed
Finished
Logging off
```

But If I look at the NoIP website, it shows Redemption in 4 days:
![image](https://github.com/simao-silva/noip-renewer/assets/108118507/c2d2bb6a-6583-4a51-bad8-8f90ff2bcd60)

I pulled the newest image of simaofsilva/noip-renewer
Any ideas about this?

**Comment by simao-silva** [comment]
Hi,
From time to time, as far as I know, NOIP requires an extra step on confirmation, Can you try clicking on the "Confirm" button and see if the host is confirmed or if you are redirect to a follow-up page?

**Comment by cfr2305** [comment]
Hi,
Thank you for the feedback.

OK. Yes if I click on Confirm I get this screen:
![image](https://github.com/simao-silva/noip-renewer/assets/108118507/71a7d655-295d-4659-b3bf-938195125965)



And If I go back and do it again, I get this screen here:
![image](https://github.com/simao-silva/noip-renewer/assets/108118507/ced86dc9-ce8e-4aba-aa45-80a39a50adf2)


Is there a solution for this "extra step"?

**Comment by simao-silva** [comment]
Given that extra step has a captcha, that will not be possible, unfortunately.

**Comment by cfr2305** [comment]
OK, that's to bad. Would it be possible to write something in the logs, if the captcha occurs, so that you see that it could not be renewed?
Because the log shows this here:

`1 host confirmed`

**Comment by simao-silva** [comment]
I will try add something once I am able to reproduce the scenario.
