### ISSUE TITLE
Login button has changed. Please contact support.

### ISSUE THREAD

**Issue by daNutzzzzz** [simao-silva/noip-renewer#27]
Hi,

Im seeing this in the logs, anyone else?

```Login button has changed. Please contact support.```

noip-renewer:latest

**Comment by daNutzzzzz** [comment]
ok im re-opening as its hit and miss of this runs successfully or i get the above error. 

```Time: Wed Mar 15 11:25:55 UTC 2023
Opening browser
Login button has changed. Please contact support.

Time: Wed Mar 15 11:26:30 UTC 2023
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off

Time: Wed Mar 15 11:44:04 UTC 2023
Opening browser
Login button has changed. Please contact support.

Time: Wed Mar 15 11:48:28 UTC 2023
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off

Time: Wed Mar 15 11:50:37 UTC 2023
Opening browser
Login button has changed. Please contact support.

Time: Wed Mar 15 11:52:21 UTC 2023
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off

Time: Wed Mar 15 11:57:04 UTC 2023
Opening browser
Login button has changed. Please contact support.

Time: Wed Mar 15 11:59:35 UTC 2023
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off
```

**Comment by simao-silva** [comment]
Hi,

I have not been able to replicate this issue. However, when I was testing this script intensely, I notice that NOIP may block or add a robot verification when multiple requests are done in a short period of time so my recommendation is to run this more sporadically.

**Comment by daNutzzzzz** [comment]
> 

ok thanks., I'll adjust my run schedule and monitor. cheers

**Comment by simao-silva** [comment]
Have you tried to login in NOIP UI? Did you have to solve a captcha?

**Comment by spencerwongfeilong** [comment]
Just deployed the container and I can confirm I am having the same issue. 

`Login button has changed. Please contact support.`

**Comment by BlaydeRunner08** [comment]
Also just deployed the container, same issue.  when logging in to noip, I received no captcha, no other prompts
