### ISSUE TITLE
new user -- cron error from synology nas

### ISSUE THREAD

**Issue by D4rkT1m0** [simao-silva/noip-renewer#28]
hello, i just installed this docker container in my synology nas,

when i launch the execution command from the task scheduler i got an error.

i follow your instruction in a previous issue to remove '-t' and i tried:

docker run --rm -i simaofsilva/noip-renewer 'user' 'password'
and
docker run --rm simaofsilva/noip-renewer 'user' 'password'

i also tried
docker run --rm -i simaofsilva/noip-renewer:latest 'user' 'password'
and
docker run --rm simaofsilva/noip-renewer:latest 'user' 'password'

the response:
Le planificateur de tâches a terminé une tâche planifiée.

Tâche : No-Ip Renewal
Heure de début : Thu, 13 Apr 2023 20:54:22 GMT
Heure d'arrêt : Thu, 13 Apr 2023 20:54:52 GMT
État actuel : 0 (Normal)
Sortie/erreur standard :
Opening browser
Login successful
Confirming hosts phase
Error: Message: The element reference of is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5
StaleElementReferenceError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:461:5
element.resolveElement@chrome://remote/content/marionette/element.sys.mjs:674:11
evaluate.fromJSON@chrome://remote/content/marionette/evaluate.sys.mjs:255:31
evaluate.fromJSON@chrome://remote/content/marionette/evaluate.sys.mjs:263:29
evaluate.fromJSON@chrome://remote/content/marionette/evaluate.sys.mjs:263:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:74:34

Logging off

thanks for your help

**Comment by D4rkT1m0** [comment]
so i connected to the website

i had "redemption days 7"

so i tried to manually confirm

i launch again the the scheduled task from my synology

and the response was:

Tâche : No-Ip Renewal
Heure de début : Thu, 13 Apr 2023 21:34:49 GMT
Heure d'arrêt : Thu, 13 Apr 2023 21:35:17 GMT
État actuel : 0 (Normal)
Sortie/erreur standard :
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off

do you think the initial error came from the fact i was in redemption day?

**Comment by simao-silva** [comment]
It is hard to tell since NOIP has captcha mechanisms and may do changes in HTML code.
