### ISSUE TITLE
Can't run 'docker build' script on Windows

### ISSUE THREAD

**Issue by senglory** [simao-silva/noip-renewer#29]
Hi, 

I get the following error when I try to execute the 'docker build ' script:

> C:\prj\>docker build -t simaofsilva/noip-renewer .
> [+] Building 0.4s (2/2) FINISHED
> => [internal] load build definition from Dockerfile
> => transferring dockerfile: 2B
> => [internal] load .dockerignore
> => transferring context: 2B
> failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2174070297/Dockerfile: no such file or directory 
> 

What should I do to have it fixed?

**Comment by simao-silva** [comment]
Hi,

Currently, I do not support Windows. In addition to change the base image, I have to change the commands to install the necessary requirements. Still, feel free to contribute and add a version supporting Windows.
