### ISSUE TITLE
Can't log in 

### ISSUE THREAD

**Issue by RomyxBaps** [simao-silva/noip-renewer#3]
Hi,

I have an error when i launch the docker run command. It cannot log in on noip website : 
```
docker run --rm -it simaofsilva/noip-renewer "xxxx@yyyyy.zz" "here_is_my_password"
Opening browser
Login page
Error: cannot login. Check if account is not blocked.
```
I tried with ' " ' also and it's the same.
I don't have special character on my password too.

**Comment by lumascet** [comment]
+1, having the same issue

**Comment by simao-silva** [comment]
Hi,

The error is due to Selenium's delay in open the hosts URL. I believe the knew version corrects this issue. Can you confirm it?

**Comment by RomyxBaps** [comment]
Okay, very nice ! I have no more errors.
But what can tell me than my hostname was really "confirm" ? It's only say "Finished".

**Comment by simao-silva** [comment]
If a host is confirmed you will see the message `Host "name of the host" confirmed`. If it only says `Finished` and no confirmed hosts message were printed that means that no hosts were available to confirm and the script is over.

**Comment by RomyxBaps** [comment]
Oh ! Okay, welle thank you ! Have a nice day.
