### ISSUE TITLE
noip renewer not working, hanging at "opening browser"

### ISSUE THREAD

**Issue by alirz1** [simao-silva/noip-renewer#32]
I've been using this on my synology NAS in a docker for several months and its been running fine. However as of few days ago i notice it doesnt seem be working.. If i run this via terminal, i provide the credentials but then it hangs at saying "opening browser".
I normally run this via the docker command :docker run --rm -it simaofsilva/noip-renewer:<TAG> <EMAIL> <PASSWORD>

That also seems to be hang with no output about whats going on

**Comment by simao-silva** [comment]
Does it happen only on your Synology NAS or in your laptop as well? I never had the opportunity to test it on a NAS so I am not aware of potential restrictions those systems have.

**Comment by alirz1** [comment]
It’s running in a docker on the nas and had been running fine for months. Nothing has changed on the nas. I don’t have a setup on a laptop to test unfortunately.
Are their any logs I can provide?

**Comment by alirz1** [comment]
Well this issue still affect me running in a docker. its set to trigger at 8am. i realize it takes exactly 12 min every time its executed. This only started happening a few weeks ago, prior to that it used to execute within a min.

**Comment by D4rkT1m0** [comment]
I have the same issue.
I run it in Docker, on a synology NAS.
task planer once every week (every monday at 14:58 (2:58 PM))
i got the same message:
Le planificateur de tâches a terminé une tâche planifiée.

Tâche : No-Ip Renewal
Heure de début : Mon, 19 Jun 2023 14:58:01 GMT
Heure d'arrêt : Mon, 19 Jun 2023 14:58:17 GMT
État actuel : 1 (Interrompu)
Sortie/erreur standard :
Opening browser
Login button has changed. Please contact support. 

but, when I manually execute the planned task, i works perfectly

my script is:
docker run --rm simaofsilva/noip-renewer 'email' 'password'

hope it helps

**Comment by simao-silva** [comment]
When you ran it manually was it on the Synology as well?

**Comment by alirz1** [comment]
Yes

**Comment by simao-silva** [comment]
I am unable to reproduce this. My recommendation is to build the image locally and test it throughout a set period of time to see if you can find a hint on what the problem might be.

**Comment by alirz1** [comment]
Today I got the following error

Start time: Thu, 06 Jul 2023 23:00:01 GMT
Stop time: Thu, 06 Jul 2023 23:14:19 GMT
Current status: 1 (Interrupted)
Standard output/error:
Traceback (most recent call last):
File "//renew.py", line 129, in
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off


browser.get(LOGOUT_URL)
File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 449, in get
self.execute(Command.GET, {"url": url})
File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
self.error_handler.check_response(response)
File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Navigation timed out after 300000 ms
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:183:5
TimeoutError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:503:5
bail@chrome://remote/content/marionette/sync.sys.mjs:213:19

**Comment by D4rkT1m0** [comment]
I noticed that the docker container in the synology have no access to internet.
I don't know now how to setup this up, but I'm on it.

once i find the right setup on the synology "Container manager" app, i'll post here.

maybe the message "opening browser" could be more specific in case that the docker container have or not internet access.

cheers

**Comment by alirz1** [comment]
> I noticed that the docker container in the synology have no access to internet. I don't know now how to setup this up, but I'm on it.
> 
> once i find the right setup on the synology "Container manager" app, i'll post here.
> 
> maybe the message "opening browser" could be more specific in case that the docker container have or not internet access.
> 
> cheers

I had this issue when i upgraded my synology to dsm 7.2. Turns out I had to set a dns server under the synologys network interface settings.

**Comment by D4rkT1m0** [comment]
@alirz1, thank you so much for this answer.
I am in DSM 7.2 also,
i tried to set this up in **control panel/network/general/** you have to enable the manual setting for the dns.
i used the cloudflare one with success (1.1.1.1)
