### ISSUE TITLE
noip-renewer weird container size

### ISSUE THREAD

**Issue by trablin45** [simao-silva/noip-renewer#33]
I've noticed today that my docker didn't allow me to create new containers because it was "full". I prune the system, gained nothing (all unused volumes and images where already removed) then proceed to check the image size of each container, noip-renewer was taking 15GB (wtf) in just 3 days. What's going on? I was using :debian 
![image](https://github.com/simao-silva/noip-renewer/assets/92314530/dd1c8af1-60d2-49b1-8df7-bbf65e915a1a)

**Comment by alirz1** [comment]
i think theres something wrong with this right now. My update command seems to hang for hours, i seems to get stuck on some php stuff. Looking at the log you mentioned, looks to be a php issue also. Not sure if the dev is active for this?

**Comment by simao-silva** [comment]
I have being running the new image with digest `074312aec5e91ca8bb486c17fc540bc73cf69acac3d95736d3dfd4d9393b44b5` in the past days without any issues. Are you running this on your desktop/laptop or on other environment?
