### ISSUE TITLE
Option: support for multiple no-ip account with multiple hosts

### ISSUE THREAD

**Issue by XtremeCoder007** [simao-silva/noip-renewer#34]
It would be nice if it could support multiple no-ip accounts with multiple hosts on each account.

Needs some altering of the current script and might need to destroy browser data every time or switch session cookies.

Providing the accounts can be either by filling in each account manually or by exposing a directory to host that contains a .csv with all the account info.

**Comment by simao-silva** [comment]
Hi,
I will not support this at the moment. However, feel free to open a PR to add this capability.
