### ISSUE TITLE
Error at login

### ISSUE THREAD

**Issue by eliaspizarro** [simao-silva/noip-renewer#35]
# docker run --rm -it simaofsilva/noip-renewer:latest my@mail.com mypass

Opening browser
Login button has changed. Please contact support.

simaofsilva/noip-renewer   latest    c3d6614aef0f

**Comment by simao-silva** [comment]
Hi,

This error still happens? I tested on my side and did not have any error.

**Comment by dkrjvi** [comment]
Hi, yes, still (for me).
![image](https://github.com/simao-silva/noip-renewer/assets/46902834/5b4b561e-51e9-413a-8787-4928bf7edd4e)

**Comment by simao-silva** [comment]
Are you running it on your laptop or a Raspberry Pi?

**Comment by dkrjvi** [comment]
laptop

**Comment by spencerwongfeilong** [comment]
I have this issue too. Never had it working before. Running on a NAS with docker.

**Comment by eliaspizarro** [comment]
runing ok in this latest

**Comment by darcy543** [comment]
Is there a fix for this? I'm getting the same error using 'latest'.

**Comment by simao-silva** [comment]
@darcy543 could you try running the image with tag `noip-renewer:c833dac-debian` and see if the problem still persists?

**Comment by dkrjvi** [comment]
@simao-silva , I have the same issue as darcy543 and I got the below when running the  image noip-renewer:c833dac-debian:
```
Status: Downloaded newer image for simaofsilva/noip-renewer:c833dac-debian
docker.io/simaofsilva/noip-renewer:c833dac-debian

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview simaofsilva/noip-renewer:c833dac-debian
Opening browser
Traceback (most recent call last):
  File "//renew.py", line 62, in <module>
    browser = webdriver.Firefox(options=browser_options, service=service)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
```

**Comment by simao-silva** [comment]
Please try again with tags 4286f44-alpine or 4286f44-debian.

**Comment by dkrjvi** [comment]
I tried the `latest ` tag first and this time it worked fine for me. Cheers!

latest: Pulling from simaofsilva/noip-renewer
96526aa774ef: Already exists
9875af95546d: Pulling fs layer
9875af95546d: Extracting  32.77kB/622.3kB
9875af95546d: Pull complete
69babf7e971f: Downloading  373.7kB/11.55MB
69babf7e971f: Pull complete
ba93e141e36c: Pull complete
f0588e5d3d11: Pull complete
204c428dc5b0: Pull complete
c75fd6080f41: Pull complete
07661391457a: Pull complete
Digest: sha256:54d8b093c5b75f28543c12b459750b0f7af463ef5e8a6363b3ad775c1049170d
Status: Downloaded newer image for simaofsilva/noip-renewer:latest
docker.io/simaofsilva/noip-renewer:latest
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off
