### ISSUE TITLE
Option to turn off google translate

### ISSUE THREAD

**Issue by cyanue** [simao-silva/noip-renewer#58]
In somewhere, google translate was forbidden, to access it will cause error like attachment:
_Error: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=en&sl=auto&q=Modify (Caused by ConnectTime..._

![error](https://github.com/simao-silva/noip-renewer/assets/68370558/9b1c7c42-ef52-4706-90e8-c8144a6e53b0)

Can you set an option to turn off it?

**Comment by simao-silva** [comment]
That seems to be an issue with your environment. If you cannot access Google Translate most likely you will face a similar error when trying to access No-IP. 
Currently, I will not add such option. However, feel free to open a PR to add that option.
