### ISSUE TITLE
'no such element' error since 2022-01-17

### ISSUE THREAD

**Issue by GitMeier** [simao-silva/noip-renewer#7]
This is from my log entries:

`
******************************
******************************
Mon 17 Jan 2022 10:00:01 AM CST
Mon 17 Jan 2022 10:07:01 AM CST
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off
******************************
******************************
Mon 17 Jan 2022 11:00:01 AM CST
Mon 17 Jan 2022 11:46:01 AM CST
Opening browser
Login successful
Confirming hosts phase
Error:  Message: no such element: Unable to locate element: {"method":"css selector","selector":"button"}
  (Session info: headless chrome=91.0.4472.164)
Logging off
******************************
`
Seems they changed the page layout again?

Still worked on 2022-01-17 at 10:07:01 AM CST

Failed the first time (for me) on 2022-01-17 at 11:46:01 AM CST

**Comment by simao-silva** [comment]
The error was related to the ad `FREE TrustCor Standard DV SSL Certificate` showed at the end of the domains list. I've also encountered this error last week but got busy. Sorry for the delay.
