### ISSUE TITLE
'Login button has changed. Please contact support.'

### ISSUE THREAD

**Issue by dkrjvi** [simao-silva/noip-renewer#8]
Hi Simao Silva, 
What a great solution you've created! worked like a charm until recently, but now when I run it I get this:
___________________
Opening browser
Login button has changed. Please contact support.
___________________

Any idea why? Let me know if any additional info is needed.
Rgrd.

**Comment by simao-silva** [comment]
That message is due to the changes that NO-IP does to the HTML code. However, I've been able to run the latest image without any errors. Can you run the following commands and post the logs if any issues occur? Don't forget to hide any sensitive information. 
```
docker run -it --rm simaofsilva/noip-renewer:latest
docker run -it --rm simaofsilva/noip-renewer:slim
docker run -it --rm simaofsilva/noip-renewer:alpine
```

**Comment by dkrjvi** [comment]
I get the same result as before on both commands:
/usr/bin/docker run --rm -it --name noip-renew simaofsilva/noip-renewer:alpine "$NOIP_USER" "$NOIP_PASS"
Opening browser
Login button has changed. Please contact support.
____________________________________________________________
/usr/bin/docker run --rm -it --name noip-renew simaofsilva/noip-renewer:slim "$NOIP_USER" "$NOIP_PASS"
Opening browser
Login button has changed. Please contact support.

**Comment by simao-silva** [comment]
@dkrjvi please paste the output of the following:
```
docker run -it --rm simaofsilva/noip-renewer:debug
```

**Comment by dkrjvi** [comment]
@simao-silva. here you go: 
```
/usr/bin/docker` run --rm -it simaofsilva/noip-renewer:debug "$NOIP_USER" "$NOIP_PASS"
Opening browser
Printing source code for debug



</h2>
                            <p class="darkgrey"><small>If you are not currently a registered user of NoIP.com and would like to be for <strong> FREE</strong>, <a href="https://www.noip.com/sign-up"> register</a> as a new user.</small></p>
                        </div>

                        <div class="col-sm-8 col-sm-offset-2">
                            
                            
                            <form method="post" action="https://www.noip.com/login" id="clogs" class="row">
                              <input type="hidden" name="_token" value="Q4yCHa19rjeo8sZgil1lp86gpNlgDnEHKUFdyn7V">                                                            <input class="col-sm-12" name="username" type="text" maxlength="50" value="" placeholder="Username or Email">

                                <input class="col-sm-12" name="password" type="password" placeholder="Password" autocomplete="off">
                                <input type="hidden" name="submit_login_page" value="1">
                                <input type="hidden" id="hash-input" name="intended_hash" value="">
                                                                    <input id="clogs-captcha-token" name="g-recaptcha-response" type="hidden">
<button type="submit" id="clogs-captcha-button" class="nomarg col-sm-12 button pull-right">
    Log In
</button>

<script src="https://



Login button has changed. Please contact support. 

```

**Comment by simao-silva** [comment]
I don't know why but I get the same output as you but in my case the button is found. I am trying a new approach. Can you please see if running the command below fixes your problem? 
```
docker run --rm -it simaofsilva/noip-renewer:debug-v2
```

**Comment by simao-silva** [comment]
Have you tried to use it without the variables?

**Comment by dkrjvi** [comment]
Yes, the same.
```
 /usr/bin/docker run --rm -it simaofsilva/noip-renewer:debug-v2
Email: xxx@xxxx.com
Password:
Opening browser
Login button has changed. Please contact support.
```

**Comment by simao-silva** [comment]
Try running the following command and check if the output images have anything strange. 
```
docker run -it --rm -v "some-local-dir":/photos simaofsilva/noip-renewer:debug-v3
```
The output should be like the image below filled with your email and password. 
<img src="https://i.ibb.co/b5SYDSq/login.png" width="100" height="100">

**Comment by dkrjvi** [comment]
Run this:
`/usr/bin/docker run --rm -it -v "/mnt/c/test/":/photos simaofsilva/noip-renewer:debug-v3 "$NOIP_USER" "$NOIP_PASS"`

and I got these two blank files:
![login1](https://user-images.githubusercontent.com/46902834/155858150-43d8376a-cf8b-45f0-ae63-9a57d87447b9.png)
![login2](https://user-images.githubusercontent.com/46902834/155858152-057ea4f2-fa2f-4841-b391-85d2b235a300.png)

**Comment by simao-silva** [comment]
That is strange. For some reason you are not able to open the No-IP website properly. From the way you mounted the volume it seems that you are using docker in WSL. Is that correct? Even so, I ran it on WSL without any issues. 
I don't how to fix your issue since I am unable to replicate it.

**Comment by dkrjvi** [comment]
Yes, I use Docker Desktop and WSL Ubuntu 20.04 on Windows 10 - As I said it work perfect in the past until recently.
I will check if the issue persist by testing different machines with Windows/Linux and advise on my results.

**Comment by dkrjvi** [comment]
Well I checked this on different scenarios and the bottom line is that the issue is on my end. 
I'm using pihole as a DNS filter on my home network and it seems when the address [www.google-analytics.com](www.google-analytics.com) was blocked this issue occurred. 
I'm not clear why this specific web address causes this but once it was whitelisted the script worked as expected.
Anyway, I appreciate your time, effort and patience to assist me on this.
Thank you! and again great script! :-)
