### ISSUE TITLE
Can it still work?

### ISSUE THREAD

**Issue by lowking** [simao-silva/noip-renewer#86]
my docker image:
```
simaofsilva/noip-renewer   latest       f020469e6a85   3 days ago      472MB
```
log:
```
Opening browser
Login successful
Confirming hosts phase
Checking if host "***" needs confirmation
Host "***" confirmed
1 host confirmed
Finished
Logging off
```
It doesn't work for me, Still need to confirm.

**Comment by pedstm** [comment]
Works for me.

**Comment by simao-silva** [comment]
@lowking was the host under the 30 days confirmation period?

**Comment by lowking** [comment]
> @lowking was the host under the 30 days confirmation period?

Of course. I confirmed it manually.
I've been using it[this](https://hub.docker.com/r/moebiuss/noip-renew) util it went wrong.

**Comment by simao-silva** [comment]
When you confirm it manually were you redirected to some confirmation page after the first click to confirm the renovation?

**Comment by lowking** [comment]
> When you confirm it manually were you redirected to some confirmation page after the first click to confirm the renovation?

After this issue occurred, I manually clicked the Confirm button several times to see if there was a verification, but it was jump to the page asking me to upgrade the plan(as usual), then robot verification appeared after many attempts.

**Comment by simao-silva** [comment]
That is why it did not work. That behaviour is not yet supported since it does appear very often. That being said, everything is working as expected.
