### ISSUE TITLE
Error: cannot login. Check if account is not blocked.

### ISSUE THREAD

**Issue by dkrjvi** [simao-silva/noip-renewer#9]
Hi Simao Silva,
I started receiving this error message recently.

```
sudo docker run --rm -it simaofsilva/noip-renewer:latest [USER] [PASS]
Opening browser
Error: cannot login. Check if account is not blocked.
Logging off

```
I got the same error when I run this on two different computers with different network connection to the internet.
Manual login to noip site is fine with the same credentials.

If it helps, I also used the following image (from your previous  assistance :-)) which also creates two PNG files (with my correct user credentials) 

```
sudo docker run --rm -it -v "/home/user/test":/photos simaofsilva/noip-renewer:debug-v3 [USER] [PASS]
Opening browser
Error: cannot login. Check if account is not blocked.
Logging off

```
![login1](https://user-images.githubusercontent.com/46902834/160464094-fe7a8a40-51f9-4dee-8325-c2a836134061.png)

![login2](https://user-images.githubusercontent.com/46902834/160464099-7cf9469e-3200-43b3-943e-87224adf742e.png)

I will appreciate for any pointers to resolve this and please let me know if any additional info is needed.

Kind regards,
dkrjvi

**Comment by simao-silva** [comment]
No-IP has changed stuff again. Please upgrade to the new image.

**Comment by jvidkr** [comment]
Hi @simao-silva , I pulled the latest image a few  moments ago but I got the same error as before.
![image](https://user-images.githubusercontent.com/101793599/160648660-586d0856-2e81-497b-922c-8048b5ba78a9.png)

**Comment by simao-silva** [comment]
I don't know how to help since I cannot reproduce the error. In all my devices on different locations the image works as expected.

**Comment by dkrjvi** [comment]
Hi, 
I 'm able to run the script successfully with the latest image for a couple of weeks now - so it seems this issue as been resolved by itself. :-)
Thank you anyway @simao-silva  for your support.
